oscap_report/cli.py, oscap_report/html_report/report_generator.py, oscap_report/html_report/templates/evaluation_characteristics.html, oscap_report/html_report/templates/oval_graph.html, oscap_report/html_report/templates/rule_detail.html, oscap_report/html_report/templates/rule_results.html, oscap_report/html_report/templates/rules_overview.html, oscap_report/scap_results_parser/oval_definition_parser/info_of_test_parser.py, oscap_report/scap_results_parser/scap_results_parser.py
This PR removes white spaces and not selected rules from the generated reports. The size of the generated report was reduced by up to 30%.
=> Remove white space

oscap_report/html_report/templates/base_report.html, oscap_report/html_report/templates/evaluation_characteristics.html, oscap_report/html_report/templates/oval_graph.html, oscap_report/html_report/templates/rule_detail.html, oscap_report/html_report/templates/rule_results.html, oscap_report/html_report/templates/rules_overview.html, oscap_report/html_report/templates/severity_of_failed_rules.html
This PR changes small detail in the HTML report:
- Search of the rule is executed by pressing enter
- Bold text in tables
- Message in the rule is not only text anymore 
- Removed bootstrap and using own CSS for progress bars
=> Fix details in HTML report

oscap_report/html_report/templates/js/interactive_script.js
This PR fixes problems with jquery searching IDs containing unexpected characters like `.-_:`.
This problem you can invoke with a test file `tests/test_data/arf_simple_rule_pass.xml` and pressing on show test details in the oval graph.
=> Fix jquery search by IDs

.github/workflows/package_dependency_test.yaml
This PR removes `python3` from the installation of dependencies because `python3` is installed by default.
=> Fix centos stream 9 CI

openscap_report/cli.py, openscap_report/html_report/templates/template_report.html
This PR creates a version of the report with online CSS. After using debug option ```ONLINE-CSS```. The version of this report uses the latest version of PatternFly but needs an internet connection.
=> Online CSS in debug mode

.github/workflows/release.yaml, release.sh
This PR creates a release script and a Github action. The release script updates the version, makes a tag, and uploads the changes to the upstream, where a GitHub action is performed to create a new release on Github. The Github release is a trigger for the pypi release (#85) and downstream releases for fedora(disabled because the downstream repo does not exist).
=> Automate release

openscap_report/html_report/report_generator.py, openscap_report/html_report/templates/rule_detail.html
This PR fixes the inverted logic of debug option `NO-MINIFY` and removes white spaces that are problematic to remove with regex.
=> Fix minify of html report

openscap_report/html_report/__init__.py, openscap_report/html_report/exceptions.py, openscap_report/html_report/report_generator.py, openscap_report/html_report/templates/rules_overview.html
This PR fixes the problem with counting in jinja macros that cause showing all rules instead only the first 50 rules. Other rules in the report are displayed when the user scrolls.
=> Fix the issue that causes displaying all rules

openscap_report/html_report/templates/base_report.html, openscap_report/scap_results_parser/parsers/full_text_parser.py, tests/constants.py, tests/unit_tests/test_full_text_parser.py
This PR fixes the problem with sub-element references that do not exist. This problem occurred with the ARF report generated on Fedora 37 rawhide with `openscap-1.3.6-10.fc37`, `scap-security-guide-0.1.62-3.fc37`. Reference Id in sub-element is `dangling reference to !`.
[The reproducer file](https://github.com/OpenSCAP/openscap-report/blob/42bd69684f715870b37d64bf04a8d7aa5b0596ba/tests/test_data/arf-dangling-reference-to.xml)
=> Fix sub-element reference that do not exist

docs/exts/sphinxarg/parser.py, openscap_report/cli.py
This PR improves the format of the man page.
=> Format man page

openscap_report/html_report/templates/js/interactive_script.js
This PR fixes the problem of the unexpected null value of the `FIRST_HIDDEN_ELEMENT` variable. 
How reproduce:
* It is caused by scrolling down through the report. 
* Error message will appear in the browsers Javascript console
Why:
* The report uses lazy loading to display the table with rules. When there are no more rules to show. Value of `.nextSibling` is `null`.
=> Fix FIRST_HIDDEN_ELEMENT is null

.github/workflows/package_dependency_test.yaml
This PR updates Nodejs actions.
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
=> Update Nodejs actions

.packit.yaml
This PR adds `srpm_build_deps` according to this message: All SRPMs will be built in Copr since January 2023. Please use [srpm_build_deps](https://packit.dev/docs/configuration/#srpm_build_deps) to be sure that we don't break your workflow once we switch to building all SRPMs in Copr.
=> Add srpm_build_deps to Packit config

openscap_report/scap_results_parser/oval_and_cpe_tree_builder.py, openscap_report/scap_results_parser/parsers/oval_definition_parser.py
This PR fixes errors associated with the processing of OVAL graphs and CPE graphs.
* Fixes a missing key error caused by a platform without an OVAL definition
* Fixes missing CPE graph in the report
* Fixes missing OVAL definitions in the report when not present in OVAL CPE checks
=> Fix OVAL graphs and CPE graphs

.github/workflows/codeql.yml, docs/exts/sphinxarg/ext.py, docs/exts/sphinxarg/markdown.py, docs/exts/sphinxarg/parser.py, openscap_report/cli.py, openscap_report/report_generators/html.py, openscap_report/report_generators/json.py
This PR fixes problems that the CodeQL scan found.
=> Fix CodeQL alerts

openscap_report/report_generators/html_templates/cpe_graph.html, openscap_report/report_generators/html_templates/css/style.css, openscap_report/report_generators/html_templates/js/oval_graph_generation_script.js, openscap_report/scap_results_parser/data_structures/__init__.py, openscap_report/scap_results_parser/data_structures/cpe_logical_test.py, openscap_report/scap_results_parser/data_structures/cpe_platform.py, openscap_report/scap_results_parser/data_structures/cpe_result_eval.py, openscap_report/scap_results_parser/data_structures/rule.py, openscap_report/scap_results_parser/exceptions.py, openscap_report/scap_results_parser/namespaces.py, openscap_report/scap_results_parser/oval_and_cpe_tree_builder.py, openscap_report/scap_results_parser/parsers/__init__.py, openscap_report/scap_results_parser/parsers/cpe_al_parser.py, openscap_report/scap_results_parser/parsers/oval_result_parser.py
This PR implements parsing of CPE AL.
=> CPE Applicability Language 

openscap_report/report_generators/html_templates/rule_detail.html, openscap_report/scap_results_parser/data_structures/__init__.py, openscap_report/scap_results_parser/data_structures/rule.py, openscap_report/scap_results_parser/data_structures/warning.py, openscap_report/scap_results_parser/parsers/rule_parser.py, tests/unit_tests/test_scap_result_parser.py
This PR adds a warning data class that contains the category and text of the warning.
=> Add warning category

.eslintignore, openscap_report/cli.py, openscap_report/report_generators/html_templates/cpe_graph.html, openscap_report/report_generators/html_templates/template_report.html, openscap_report/scap_results_parser/__init__.py, openscap_report/scap_results_parser/data_structures/report.py, openscap_report/scap_results_parser/exceptions.py, openscap_report/scap_results_parser/oval_and_cpe_tree_builder.py, openscap_report/scap_results_parser/parsers/group_parser.py, openscap_report/scap_results_parser/parsers/oval_result_parser.py, openscap_report/scap_results_parser/scap_results_parser.py, openscap_report/scap_results_parser/schemas/xccdf/1.2/XMLSchema.dtd, openscap_report/scap_results_parser/schemas/xccdf/1.2/cpe-language_2.3.xsd, openscap_report/scap_results_parser/schemas/xccdf/1.2/datatypes.dtd, openscap_report/scap_results_parser/schemas/xccdf/1.2/xccdf_1.2.xsd, tests/constants.py, tests/integration_tests/test_basic_usage.py, tests/integration_tests/test_cli.py, tests/test_data/plant_catalog.xml, tests/unit_tests/test_data_structure.py, tests/unit_tests/test_scap_result_parser.py
This PR fixes crashes when using the XCCDF report.
How to reproduce the problem: Use oscpa-report with XCCDF results.  
For example: `oscap-report < tests/test_data/xccdf-report.xml`
The crashes were caused by a missing part of the if condition. To avoid this problem, I created integration tests with all test files. And I discovered problems: 
* The first is that it is expected that the rule must be present in some of the groups.
* Missing selected rule definition, which should be a content issue that is fixed in later versions.
=> Fix XCCDF support

.scrutinizer.yml, json_validator.py, openscap_report/scap_results_parser/data_structures/group.py, openscap_report/scap_results_parser/data_structures/identifier.py, openscap_report/scap_results_parser/data_structures/json_transformation.py, openscap_report/scap_results_parser/data_structures/oval_definition.py, openscap_report/scap_results_parser/data_structures/profile_info.py, openscap_report/scap_results_parser/data_structures/reference.py, openscap_report/scap_results_parser/data_structures/remediation.py, openscap_report/scap_results_parser/data_structures/report.py, openscap_report/scap_results_parser/data_structures/result_of_scan.py, openscap_report/scap_results_parser/data_structures/rule.py, openscap_report/scap_results_parser/data_structures/warning.py, tests/constants.py, tests/integration_tests/test_json.py, tests/json_schema_of_report.json, tests/unit_tests/test_json_transitions.py, tox.ini
This PR expands JSON content.  It also adds:
* JSON generation tests,
* JSON schema for tests,
* creates an easy tool for validating JSON output.
It depends on #129
=> JSON content extension

tests/test_utils.py, tests/unit_tests/test_data_structure.py, tests/unit_tests/test_full_text_parser.py, tests/unit_tests/test_scap_result_parser.py
This PR improves the runtime of unit tests.
* Reorganization of the help functions that sometimes was duplicated,
* Using cache for loading files,
* Some tests have been reclassified as unit tests,
* Reduce Report generation. 
Run unit tests: `pytest -m "not integration_test"`
Used command for benchmark: `perf stat -r 10 pytest -m "not integration_test"`
183 tests
```
Performance counter stats for 'pytest -m not integration_test' (10 runs):
34 305,21 msec task-clock:u                     #    0,960 CPUs utilized            ( +-  2,00% )
0      context-switches:u               #    0,000 /sec                   
0      cpu-migrations:u                 #    0,000 /sec                   
1 454 540      page-faults:u                    #   40,731 K/sec                    ( +-  0,23% ) …
```
=> Improvements to the runtime of unit tests

openscap_report/report_generators/html_templates/rule_detail.html, openscap_report/scap_results_parser/data_structures/rule.py, openscap_report/scap_results_parser/parsers/rule_parser.py
This PR adds a weight attribute to the rule.
=>  Add a weight attribute to the rule

openscap_report/report_generators/html_templates/css/style.css, openscap_report/report_generators/html_templates/js/interactive_script.js, openscap_report/report_generators/html_templates/remedations.html, openscap_report/report_generators/html_templates/rules_overview.html, openscap_report/report_generators/html_templates/search_input.html
This PR brings improvements to the style of the report, such as:
* Improves wording in the filtering section,
* Underlines the clickable element of the remediation,
* Adds a copy button to the clipboard fix of remediation,
* Allows you to click on the rule title in the rules overview to collapse rule detail. (On hover element is underlined) 
Remediation example:
Rule overview:
=> Style adjustments of report

openscap_report/report_generators/html_templates/js/oval_graph_generation_script.js, openscap_report/scap_results_parser/data_structures/__init__.py, openscap_report/scap_results_parser/data_structures/oval_object.py, openscap_report/scap_results_parser/parsers/oval_object_parser.py
This PR adds a message of the collected OVAL object. Usually, this message explains why the OVAL test ended with an error result.
Example:
=> Add collected OVAL object messages

openscap_report/scap_results_parser/parsers/cpe_al_parser.py, tests/test_utils.py, tests/unit_tests/test_cpe_al_parser.py
This PR adds support for the `check-fact-ref` element in CPE-AL. And PR fixes a logical test negation parsing problem that was discovered by the new tests.
Fixes: #149
=> Add support for the `check-fact-ref` element in CPE-AL

openscap_report/report_generators/html_templates/oval_definition_detail.html, openscap_report/scap_results_parser/data_structures/oval_definition.py, openscap_report/scap_results_parser/parsers/oval_definition_parser.py, tests/test_utils.py
This PR adds an explanation of the result mapping between XCCDF and OVAL.
Changes:
* Adds an OVAL definition class,
* explanation of results mapping.
=> Explanation of the result mapping between XCCDF and OVAL

.packit.yaml
The main purpose of this PR is to create a separate EPEL 8 release job.  Additionally, this PR contains test synchronization.
=> Separate packit job for release in EPEL 8

openscap_report/report_generators/html.py, openscap_report/report_generators/html_templates/cpe_graph.html, openscap_report/report_generators/html_templates/js/oval_graph_generation_script.js, openscap_report/report_generators/html_templates/oval_graph.html, openscap_report/scap_results_parser/data_structures/profile_info.py, openscap_report/scap_results_parser/data_structures/rule.py, openscap_report/scap_results_parser/oval_and_cpe_tree_builder.py, openscap_report/scap_results_parser/parsers/cpe_al_parser.py, openscap_report/scap_results_parser/parsers/oval_definition_parser.py, openscap_report/scap_results_parser/parsers/oval_result_parser.py, openscap_report/scap_results_parser/parsers/rule_parser.py, openscap_report/scap_results_parser/scap_results_parser.py, tests/test_utils.py, tests/unit_tests/test_cpe_al_parser.py
This PR adds multi-check rules to the HTML report. 
Example:
Depend on: #140
=> Add multi-check rules

openscap_report/scap_results_parser/data_structures/profile_info.py, openscap_report/scap_results_parser/data_structures/rule.py, openscap_report/scap_results_parser/oval_and_cpe_tree_builder.py, openscap_report/scap_results_parser/parsers/cpe_al_parser.py, openscap_report/scap_results_parser/parsers/oval_definition_parser.py, openscap_report/scap_results_parser/parsers/oval_result_parser.py, openscap_report/scap_results_parser/parsers/rule_parser.py, openscap_report/scap_results_parser/scap_results_parser.py, tests/test_utils.py, tests/unit_tests/test_cpe_al_parser.py
This PR changes the approach of loading the OVAL results report and brings special logic to determine where is present the OVAL result report with the OVAL definitions that are used in the CPE dictionary and CPE AL. 
The OVAL result report element is selected according to the references in the rule results. The selected element is the one that is not referenced in the rule results. If multiple report elements are not referenced in the rule result, OVAL definitions for CPE are selected from all report elements. In the case of duplicate definitions, the first definition or the definition that has a result other than `not evaluated` is chosen.
=> Change loading of OVAL result reports

openscap_report/report_generators/html_templates/evaluation_characteristics.html
This PR adds non-breaking space between the scanner and the version of the scanner.
Fixes: #166
=> Add non-breaking space

openscap_report/report_generators/html_templates/rule_detail.html
This PR uses a span element instead of a link element when the href is unavailable.
Fixes: #172
=> Show references and identifier as plain text when href is unavailable

openscap_report/report_generators/html_templates/js/interactive_script.js, openscap_report/report_generators/html_templates/search_input.html
This PR adds a clear button to the search bar.
Fixes: #179
=> Implement clear button for search bar

openscap_report/report_generators/html_templates/css/style.css, openscap_report/report_generators/html_templates/js/interactive_script.js, openscap_report/report_generators/html_templates/js/oval_graph_generation_script.js
This PR adds a tooltip when the rule ID is copied to the clipboard.
Fixes: #180
=> Add Copy To Clipboard Tooltip

openscap_report/report_generators/html_templates/css/style.css, openscap_report/report_generators/html_templates/rules_overview.html
This PR relates to issue #173. The problem occurs when the window width is less than 900px because the report layout changes and the rule detail becomes scrollable.
Specifically, Firefox has user-manageable settings for displaying scrollbars, and Webkit for scrollbars is not implemented in Firefox. This makes it difficult to customize the scrollbar. Therefore, I decided to disable scrolling for the rule detail when the window width is small.
=> Disable scrollbar in rule detail

openscap-report.spec, openscap_report/report_generators/html.py, spec/rhel8/openscap-report.spec
This PR changes the requirement of redhat fonts as weak dependency and changes the logging severity of missing fonts warning.
Fixes: #184
=> Change RedHat fonts to weak dependency

openscap_report/report_generators/html_templates/base_report.html, openscap_report/report_generators/html_templates/js/interactive_script.js, openscap_report/report_generators/html_templates/template_report.html
This PR adds a button back to the top. 
Fixes: #178
=> Add button back to top of report

openscap_report/report_generators/html_templates/css/style.css, openscap_report/report_generators/html_templates/js/oval_graph_generation_script.js
This PR adds a tooltip about the evaluation of the operator to the OVAL and CPE AL operators.
=> Explain OVAL and CPE AL operators

openscap_report/report_generators/html_templates/oval_definition_detail.html
This PR renames the Result explained field to Class explained. To avoid confusion in this field.
=> Rename field Result explained to Class explained

openscap_report/report_generators/html_templates/css/style.css, openscap_report/report_generators/html_templates/template_report.html, openscap_report/scap_results_parser/data_structures/result_of_scan.py, openscap_report/scap_results_parser/parsers/scan_result_parser.py
This PR adds a tooltip that explains the computation of the score in the report. 
Fixes: #163
=> Explain the calculation of the score

generate_arf.sh, plans/integration.fmf
This PR changes the behaviour of the `./generate_arf.sh` script. The script automatically determines the content product by the CPE_NAME in `/etc/os-release`.  
Fixes: #201
=> Auto product

openscap_report/__init__.py
This PR fixes:
DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Reproducer with `tox`:
```
diff --git a/tox.ini b/tox.ini
index 8d55872..5431db5 100644
--- a/tox.ini
+++ b/tox.ini
@@ -17,6 +17,7 @@ commands =
py.test --cov=openscap_report --cov-append --cov-report=term-missing -m "not integration_test"
py.test --cov-report=term-missing -m "not unit_test"
deps =
+    setuptools>=67.6.1
pytest
pytest-cov
jsonschema
```
Fixes: #203
=> Fix deprecation warning

openscap_report/scap_results_parser/scap_results_parser.py
This PR fixes crashes caused by empty values in the Value component. It is represented as `None` instead of an empty string in the lxml parser. The value of the Value component that was used during the scan is obtained from the `set-value` elements. In this case, it represents a self-closing `set-value` tag.  
The ID of the Value component that caused the problem is `xccdf_org.ssgproject.content_value_var_pam_wheel_group_for_su`. 
Fixes: #207
=> Fix empty Value property value

openscap_report/report_generators/html_templates/css/style.css, openscap_report/report_generators/html_templates/js/oval_graph_generation_script.js, openscap_report/scap_results_parser/data_structures/oval_object.py, openscap_report/scap_results_parser/data_structures/oval_test.py, openscap_report/scap_results_parser/oval_and_cpe_tree_builder.py, openscap_report/scap_results_parser/parsers/__init__.py, openscap_report/scap_results_parser/parsers/oval_definition_parser.py, openscap_report/scap_results_parser/parsers/oval_endpoint_information_parser.py, openscap_report/scap_results_parser/parsers/oval_object_parser.py, openscap_report/scap_results_parser/parsers/oval_result_parser.py, openscap_report/scap_results_parser/parsers/oval_state_parser.py, openscap_report/scap_results_parser/parsers/oval_test_info_parser.py, openscap_report/scap_results_parser/parsers/oval_test_parser.py, openscap_report/scap_results_parser/scap_results_parser.py
This PR reworks the presentation of OVAL objects and states in the HTML report. It displays OVAL object and state definitions instead of collected objects. This helps performance, for example, when a large file system is being collected as collected objects.
The new presentation of OVAL Object and OVAL State:
Fixes: #208, #176 
Referenced variables, filters, set elements, etc. are implemented in  PR #211:
=> Rework the OVAL test details

openscap_report/report_generators/html_templates/js/oval_graph_generation_script.js, openscap_report/scap_results_parser/data_structures/__init__.py, openscap_report/scap_results_parser/data_structures/oval_test.py, openscap_report/scap_results_parser/data_structures/oval_variable.py, openscap_report/scap_results_parser/parsers/__init__.py, openscap_report/scap_results_parser/parsers/oval_endpoint_information_parser.py, openscap_report/scap_results_parser/parsers/oval_object_parser.py, openscap_report/scap_results_parser/parsers/oval_state_parser.py, openscap_report/scap_results_parser/parsers/oval_test_parser.py, openscap_report/scap_results_parser/parsers/oval_variable_parser.py
This PR deals with references to OVAL Variables and Objects, and displays embed elements such as set, concat etc... 
See the example of the new detail of the OVAL Test:
=> Resolve references to OVAL endpoints

openscap_report/report_generators/html_templates/css/style.css
This PR fixes the width of the `pre` element. The gray background of `pre` elements is not expanded.  
New lines cannot be fixed because this would change the meaning of the `pre` element. For inline code, I would suggest using the `code` element. This change is at the Content level.
=> Fix of `pre` element width

openscap_report/report_generators/html_templates/evaluation_characteristics.html, openscap_report/scap_results_parser/data_structures/result_of_scan.py, openscap_report/scap_results_parser/parsers/scan_result_parser.py, tests/json_schema_of_report.json
This PR adds target addresses to the report. 
Fixes: #165
=> Add target addresses

openscap_report/report_generators/html_templates/js/oval_graph_generation_script.js, openscap_report/scap_results_parser/data_structures/oval_test.py, openscap_report/scap_results_parser/parsers/oval_test_parser.py
This PR changes the representation of components referenced by OVAL Tests, such as Objects, States, and Variables. 
See the new representation:
Fixes: #216
=> Reorganization of OVAL Test results 

openscap_report/report_generators/html_templates/evaluation_characteristics.html, openscap_report/report_generators/html_templates/macros/list_item.html, openscap_report/report_generators/html_templates/template_report.html
This PR creates a two-tier display of Evaluation Characteristics. 
Fixes: #167
=> Presentation of evaluation characteristics

openscap_report/report_generators/html_templates/css/style.css, openscap_report/report_generators/html_templates/js/interactive_script.js, openscap_report/report_generators/html_templates/rules_overview.html, openscap_report/report_generators/html_templates/search_input.html, openscap_report/scap_results_parser/data_structures/rule.py, openscap_report/scap_results_parser/parsers/known_references.py
This PR adds the ability to search rules by reference and policy. It also adds help with tips for using search and advanced search options. 
Fixes: 
- #169 
- #171
=> Search rules by references

openscap-report.spec
The Fedora Python packaging guidelines exclude coverage checks as used in this package's tox.ini:
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_linters
Furthermore, RHEL does not include tox, but even in Fedora it does not add much value relative to its dependencies.  Calling %pytest directly is simpler and more conformant.
=> spec: avoid coverage and tox dependencies

openscap_report/scap_results_parser/parsers/profile_info_parser.py, openscap_report/scap_results_parser/parsers/shared_static_methods_of_parser.py, tests/unit_tests/test_shared_static_methods_of_parser.py
Ensure the `title` and `description` members of ProfileInfo objects are not None.
Fixes: #233
=> Fix a traceback

openscap_report/report_generators/html_templates/js/oval_graph_generation_script.js, openscap_report/scap_results_parser/data_structures/__init__.py, openscap_report/scap_results_parser/data_structures/oval_items.py, openscap_report/scap_results_parser/data_structures/oval_object.py, openscap_report/scap_results_parser/namespaces.py, openscap_report/scap_results_parser/parsers/__init__.py, openscap_report/scap_results_parser/parsers/oval_items_parser.py, openscap_report/scap_results_parser/parsers/oval_object_parser.py, tests/unit_tests/test_oval_items_parser.py
Currently, the "Show test details" section displays definition of OVAL Object and OVAL State. This patch will add also displaying OVAL Items collected from the system for the given OVAL Object. This is a very popular feature of the old report which I think will be useful also in the new report because it gives detailed information about the actual state of the target.
=> Show collected items data

.github/workflows/gating.yaml
Since C8S is no longer supported, use [UBI](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux_atomic_host/7/html/getting_started_with_containers/using_red_hat_universal_base_images_standard_minimal_and_runtimes#pull_ubi_images) instead.
=> Move to UBI8 for C8S testing

openscap_report/report_generators/html_templates/js/oval_graph_generation_script.js, openscap_report/scap_results_parser/parsers/oval_endpoint_information_parser.py
- make the layout more compact to show all related data at a single
place
- For OVAL objects, create a table where each child element is
represented as a table row
- OVAL object child elements tag name is shown as first column in the row
- OVAL object child elements text data shown as second column in the row
- OVAL object child elements attributes are shown as labels
- OVAL states and OVAL variables are presented in a similar way
as OVAL objects as described above
- make sure the test details window is standalone
Any suggestions are welcome. I would appreciate advice on the classes of the HTML elements. Feel free to come up with layout suggestions. I'm also interested in you experience in more complex OVAL tests. Please try it out and report back.
=> Improve layout of test details window

openscap_report/report_generators/html_templates/oval_definition_detail.html, openscap_report/scap_results_parser/data_structures/oval_definition.py, openscap_report/scap_results_parser/parsers/oval_definition_parser.py, tests/test_utils.py
In normal SCAP content, the OVAL definitions have always class attribute set to compliance. It isn't necessary to show this information in every rule in HTML report and add a long description, it only creates noise.
=> Remove OVAL definition class information

openscap_report/scap_results_parser/data_structures/remediation.py, openscap_report/scap_results_parser/parsers/rule_parser.py
This change will cause that Anaconda and Kickstart remediation types will not be shown in the HTML report. Anaconda remediations are consumed only by OSCAP Anaconda Addon. Kickstart remediations are consumed by OpenSCAP to generate a kickstart. It isn't useful to the user at all to see or copy these remediation types, they don't have any use for them. To reduce the unnecessary information in the report, we won't include them in the report.
=> Hide some remediation types

openscap_report/report_generators/html_templates/rule_detail.html
With this patch, we won't show OVAL details for notapplicable rules. The reason is that if a rule is notapplicable the OVAL isn't evaluated at all. Also, the users are interested only in the CPE OVAL.
Fixes: #241
=> Do not show OVAL details for notapplicable rules

openscap_report/report_generators/html_templates/js/oval_graph_generation_script.js
This commit will prevent horizontal scrollbars on tables that are vertically organized therefore they don't need horizontal scrollbars.
=> Prevent unwanted scrollbars
