OpenSCAP/openscap-report

- .gitignore
- oscap_report/cli.py
- oscap_report/old_html_report_style/report_generator.py
- oscap_report/scap_results_parser/scap_results_parser.py
This PR creates a command line API.
> Create a command line API

- .gitignore
- .pylintrc
- oscap_report/cli.py
- oscap_report/old_html_report_style/report_generator.py
- oscap_report/scap_results_parser/scap_results_parser.py
- oscap_report/scap_results_parser/schemas/arf/1.1/asset-identification_1.1.0.xsd
- oscap_report/scap_results_parser/schemas/arf/1.1/asset-reporting-format_1.1.0.xsd
- oscap_report/scap_results_parser/schemas/arf/1.1/reporting-core_1.1.0.xsd
- oscap_report/scap_results_parser/schemas/arf/1.1/xAL.xsd
- oscap_report/scap_results_parser/schemas/arf/1.1/xNL.xsd
- oscap_report/scap_results_parser/schemas/common/catalog.xsd
- oscap_report/scap_results_parser/schemas/common/xlink.xsd
- oscap_report/scap_results_parser/schemas/common/xml.xsd
- oscap_report/scap_results_parser/schemas/common/xmldsig-core-schema.xsd
- oscap_report/scap_results_parser/schemas/cpe/2.0/cpe-dictionary_2.0.xsd
- oscap_report/scap_results_parser/schemas/cpe/2.1/cpe-dictionary_2.1.xsd
- oscap_report/scap_results_parser/schemas/cpe/2.2/cpe-dictionary_2.2.xsd
- oscap_report/scap_results_parser/schemas/cpe/2.3/cpe-dictionary_2.3.xsd
- oscap_report/scap_results_parser/schemas/cpe/2.3/cpe-language_2.3.xsd
- oscap_report/scap_results_parser/schemas/cpe/2.3/cpe-naming_2.3.xsd
- requirements.txt
- setup.py
This PR adds to the parser ability to check if the report is an ARF report and creates an error handling.
> ARF validation and error handling

- oscap_report/html_report/report_generator.py
- tests/test_cli.py
This PR fixes problems with storing reports and using the static method in tests.
> Fix storing reports

- oscap_report/html_report/templates/remedations.html
- oscap_report/html_report/templates/rule_detail.html
- oscap_report/html_report/templates/rules_overview.html
- oscap_report/html_report/templates/template_report.html
- oscap_report/scap_results_parser/data_structures.py
- oscap_report/scap_results_parser/scap_results_parser.py
This PR adds the ability to parse rules and show them in an HTML report.
> Parse rules

- oscap_report/html_report/templates/base_report.html
- oscap_report/html_report/templates/evaluation_characteristics.html
- oscap_report/html_report/templates/remedations.html
- oscap_report/html_report/templates/rule_detail.html
- oscap_report/html_report/templates/rule_results.html
- oscap_report/html_report/templates/rules_overview.html
- oscap_report/html_report/templates/score_bar.html
- oscap_report/html_report/templates/severity_of_failed_rules.html
- oscap_report/html_report/templates/summary_banner.html
- oscap_report/html_report/templates/template_report.html
- oscap_report/scap_results_parser/data_structures.py
- oscap_report/scap_results_parser/scap_results_parser.py
This PR creates an HTML report look and add statistic graphs about the scan to the HTML report.
> CSS in HTML

- oscap_report/html_report/templates/oval_graph.html
- oscap_report/html_report/templates/rule_detail.html
- oscap_report/scap_results_parser/data_structures.py
- oscap_report/scap_results_parser/exceptions.py
- oscap_report/scap_results_parser/oval_definition_parser/oval_definition_parser.py
- oscap_report/scap_results_parser/scap_results_parser.py
This PR  adds OVAL graphs to the report.
> OVAL graphs in the report

- .scrutinizer.yml
This PR setup Scrutinizer coverage.
> Setup Scrutinizer coverage

- oscap_report/html_report/templates/oval_graph.html
- oscap_report/scap_results_parser/data_structures.py
- oscap_report/scap_results_parser/namespaces.py
- oscap_report/scap_results_parser/oval_definition_parser/info_of_test_parser.py
- oscap_report/scap_results_parser/oval_definition_parser/oval_definition_parser.py
This PR contains a parser for info on the OVAL test.
> Parser for info on the OVAL test

- oscap_report/html_report/templates/info_oval_test.html
- oscap_report/html_report/templates/oval_graph.html
- oscap_report/scap_results_parser/data_structures.py
- oscap_report/scap_results_parser/namespaces.py
- oscap_report/scap_results_parser/oval_definition_parser/info_of_test_parser.py
- oscap_report/scap_results_parser/oval_definition_parser/oval_definition_parser.py
This PR adds info on the OVAL test in the report.
> Info on the OVAL test add to report

- oscap_report/html_report/templates/info_oval_test.html
- oscap_report/html_report/templates/oval_graph.html
- oscap_report/scap_results_parser/data_structures.py
- oscap_report/scap_results_parser/namespaces.py
- oscap_report/scap_results_parser/oval_definition_parser/info_of_test_parser.py
- oscap_report/scap_results_parser/oval_definition_parser/oval_definition_parser.py
- oscap_report/scap_results_parser/scap_results_parser.py
This PR adds the CPE OVAL tree to the OVAL tree.
> CPE in OVAL tree

- tox.ini
This PR changes settings for code style tests.
> Set only warning for code style test

- oscap_report/cli.py
- oscap_report/html_report/report_generator.py
- oscap_report/html_report/templates/base_report.html
- oscap_report/html_report/templates/evaluation_characteristics.html
- oscap_report/html_report/templates/oval_graph.html
- oscap_report/html_report/templates/rule_detail.html
- oscap_report/html_report/templates/rule_results.html
- oscap_report/html_report/templates/rules_overview.html
- oscap_report/scap_results_parser/oval_definition_parser/info_of_test_parser.py
- oscap_report/scap_results_parser/scap_results_parser.py
This PR move all JavaScript code to one place.
> JavaScript code in a report in one place

- oscap_report/scap_results_parser/data_structures.py
> Remove unused code

- oscap_report/scap_results_parser/data_structures.py
- oscap_report/scap_results_parser/oval_definition_parser/oval_definition_parser.py
- oscap_report/scap_results_parser/scap_results_parser.py
- tests/constants.py
- tests/integration_tests/test_cli.py
- tests/test_data/arf-with-removed-info.xml
- tests/test_data/arf_multi_check.xml
- tests/test_data/arf_no_system_data.xml
- tests/test_data/arf_rule_and_cpe_check.xml
- tests/test_data/arf_simple_rule_fail.xml
- tests/test_data/arf_simple_rule_pass.xml
- tests/test_data/xccdf-with-removed-info.xml
- tests/test_data/xccdf_multi_check.xml
- tests/test_data/xccdf_no_system_data.xml
- tests/test_data/xccdf_rule_and_cpe_check.xml
- tests/test_data/xccdf_simple_rule_fail.xml
- tests/test_data/xccdf_simple_rule_pass.xml
- tests/unit_tests/test_data_structure.py
- tests/unit_tests/test_scap_result_parser.py
- tox.ini
This PR includes:
- New unit tests for data structures
- FIxes discovered bugs
- Disables CPE graph generating (panned to fix in other PR) 
- Reorganization of tests
- Independent execution of unit tests and integration tests
> Unit tests

- oscap_report/html_report/templates/js/interactive_script.js
- oscap_report/html_report/templates/rules_overview.html
- oscap_report/html_report/templates/search_input.html
- oscap_report/html_report/templates/template_report.html
This PR creates advanced options for search.
> Advanced search of rules

- .github/workflows/package_dependency_test.yaml
- requirements.txt
- setup.py
- test_of_the_basic_function.sh
This PR contains a GitHub action workflow for testing the basic functionality and dependency compatibility on different versions of operating systems. 
Tested on: 
- Centos Stream 9
- Fedora Rawhide
- Fedora lastest
> Setup workflow

- tests/unit_tests/test_oval_tree_eval.py
This PR creates tests for OVAL tree evaluation.
> Test OVAL tree evaluation

- tests/unit_tests/test_oval_result_eval.py
This PR creates tests for OVAL operator evaluation.
> Tests of OVAL operator evaluation

- tests/constants.py
- tests/test_data/arf_cpe_check_os_platform.xml
- tests/unit_tests/test_scap_result_parser.py
This PR contains tests for CPE check trees.
> Tests for CPE check trees

- openscap_report/html_report/templates/js/interactive_script.js
- openscap_report/html_report/templates/rule_detail.html
- openscap_report/html_report/templates/rules_overview.html
- openscap_report/html_report/templates/search_input.html
- openscap_report/scap_results_parser/data_structures/data_structures.py
- openscap_report/scap_results_parser/scap_results_parser.py
This PR contains:
* Fix missing message in rules
* Change result according to issue #39 
Fixes #39
> Result after remediaton

- openscap_report/html_report/templates/remedations.html
- openscap_report/scap_results_parser/description_parser.py
- openscap_report/scap_results_parser/remediation_parser.py
- openscap_report/scap_results_parser/rule_parser.py
- openscap_report/scap_results_parser/scap_results_parser.py
- tests/constants.py
- tests/test_data/remediations_scripts/auditd_data_retention_action_mail_acct_ansible.txt
- tests/test_data/remediations_scripts/auditd_data_retention_action_mail_acct_sh.txt
- tests/test_data/remediations_scripts/dconf_gnome_screensaver_lock_enabled_ansible.txt
- tests/test_data/remediations_scripts/dconf_gnome_screensaver_lock_enabled_sh.txt
- tests/unit_tests/test_scap_result_parser.py
This PR adds the ability to process XML tag `sub` in the text and fixes the content of remediation code.
Fixes #42
> Process XML tag `sub` in description and in remediation code

- openscap_report/cli.py
- openscap_report/html_report/__init__.py
- openscap_report/old_html_report_style/__init__.py
This PR changes imports of HTML report generators sub-packages.
> Improve imports of HTML report generators

- .flake8
- openscap_report/cli.py
- openscap_report/html_report/__init__.py
- openscap_report/old_html_report_style/__init__.py
- openscap_report/scap_results_parser/data_structures/__init__.py
> Use global ignore for F401 in `__init__.py`

- openscap_report/cli.py
- openscap_report/html_report/report_generator.py
- openscap_report/html_report/templates/base_report.html
- openscap_report/html_report/templates/js/debug_script.js
- openscap_report/html_report/templates/js/interactive_script.js
- openscap_report/html_report/templates/rules_overview.html
- openscap_report/html_report/templates/search_input.html
- openscap_report/html_report/templates/template_report.html
This PR create a button to show details of all rules. After using debug option ```BUTTON-SHOW-ALL-RULES```.
> Show all rules button in debug mode

- openscap_report/scap_results_parser/parsers/__init__.py
- openscap_report/scap_results_parser/parsers/full_text_parser.py
- openscap_report/scap_results_parser/parsers/rule_parser.py
- openscap_report/scap_results_parser/scap_results_parser.py
- tests/unit_tests/test_scap_result_parser.py
This PR fixes incomplete text of warning and rationale.
Fixes #60
> Fix incomplete text

- openscap_report/html_report/templates/base_report.html
- openscap_report/html_report/templates/js/oval_graph_generation_script.js
- openscap_report/html_report/templates/rules_overview.html
This PR contains fixes of problems:
* Missing icon before negation in OVAL graph.
* The first 50 selected rules are not displayed in the report.
> Fix bugs before release

- .github/workflows/package_dependency_test.yaml
- setup.py
https://peps.python.org/pep-0423/#overview
> Rename PyPI package to 'openscap-report' (underscores are discouraged)

- .packit.yaml
- MANIFEST.in
- openscap-report.spec
- openscap_report/__init__.py
- openscap_report/scap_results_parser/data_structures/oval_result_eval.py
This PR contains:
* Fix build of RPM.
* Fix of error found by `rpmlint` tool.
* Set variable `__version__` automatically according to the installed version of the package. 
* Add propose downstream job to packit.
* Fix problems discovered by `packit validate-config`
> Spec and package enhancement

- docs/conf.py
- docs/exts/sphinxarg/ext.py
This PR formats imports in docs with the tool `isort`.
> Format imports in docs

- openscap_report/html_report/templates/base_report.html
> Add Favicon

- .github/workflows/python-publish.yml
- openscap-report.spec
- release.sh
These PR fixes problems founded by the first release.
> Fix release details

- openscap_report/cli.py
- openscap_report/debug_settings.py
- tests/unit_tests/test_debug_settings.py
This PR enhances the class `DebugSettings` that contains settings for debugging.
> Debug settings enhancement

- .packit.yaml
This PR enables Packit job propose downstream.
> Enable propose downstream

- .pylintrc
- tests/unit_tests/test_full_text_parser.py
This PR contains:
* Update of `pylint` configuration
* Fix W1514
> Fix pylint errors

- openscap_report/report_generators/html_templates/oval_graph.html
- openscap_report/scap_results_parser/data_structures/__init__.py
- openscap_report/scap_results_parser/data_structures/oval_definition.py
- openscap_report/scap_results_parser/data_structures/oval_reference.py
- openscap_report/scap_results_parser/data_structures/rule.py
- openscap_report/scap_results_parser/oval_and_cpe_tree_builder.py
- openscap_report/scap_results_parser/parsers/__init__.py
- openscap_report/scap_results_parser/parsers/oval_definition_parser.py
- openscap_report/scap_results_parser/parsers/oval_result_parser.py
- openscap_report/scap_results_parser/parsers/oval_test_info_parser.py
- openscap_report/scap_results_parser/parsers/rule_parser.py
- tests/unit_tests/test_scap_result_parser.py
This PR implements parsing of OVAL definitions which brings additional information to the OVAL tree. Parsed information are title, version, description and comments for OVAL tree nodes.
> Enhance parsing of OVAL

- openscap_report/report_generators/html_templates/rules_overview.html
This PR replaces the empty rule title with the rule id.
> Replace the empty rule title with the rule id

- openscap_report/report_generators/html_templates/js/oval_graph_generation_script.js
- openscap_report/report_generators/html_templates/oval_definition_detail.html
- openscap_report/report_generators/html_templates/oval_graph.html
- openscap_report/report_generators/html_templates/rule_detail.html
This PR display new information about OVAL definitions. 
Depends on: #111
> OVAL enhancement: HTML report

- openscap_report/report_generators/html_templates/js/oval_graph_generation_script.js
> Move comment of OVAL nodes behind result label

- openscap_report/scap_results_parser/parsers/rule_parser.py
This PR fixes parsing of checking engine results after remediation.
> Fix parsing of checking engine results after remediation

- .github/workflows/codeql.yml
- .github/workflows/package_dependency_test.yaml
- release.sh
This PR renamed the master branch to the main branch in config files. To make the project conform to the Conscious language.
> Conscious language

- openscap_report/report_generators/html.py
- openscap_report/report_generators/html_templates/base_report.html
- openscap_report/report_generators/html_templates/css/style.css
- openscap_report/report_generators/html_templates/evaluation_characteristics.html
- openscap_report/report_generators/html_templates/profile_info.html
- openscap_report/report_generators/html_templates/rules_overview.html
- openscap_report/report_generators/html_templates/score_bar.html
- openscap_report/report_generators/html_templates/template_report.html
- openscap_report/scap_results_parser/data_structures/__init__.py
- openscap_report/scap_results_parser/data_structures/profile_info.py
- openscap_report/scap_results_parser/data_structures/report.py
- openscap_report/scap_results_parser/data_structures/result_of_scan.py
- openscap_report/scap_results_parser/oval_and_cpe_tree_builder.py
- openscap_report/scap_results_parser/parsers/__init__.py
- openscap_report/scap_results_parser/parsers/group_parser.py
- openscap_report/scap_results_parser/parsers/profile_info_parser.py
- openscap_report/scap_results_parser/parsers/report_parser.py
- openscap_report/scap_results_parser/parsers/scan_result_parser.py
- openscap_report/scap_results_parser/scap_results_parser.py
- tests/integration_tests/test_cli.py
- tests/unit_tests/test_debug_settings.py
- tests/unit_tests/test_scap_result_parser.py
This PR adds a description of the profile and applicable CPE platforms for the profile and CPE platforms that were found to be applicable on the evaluated machine.
> Info about profile

- .pylintrc
- tox.ini
This PR reduces the usage of external tools in the tox test suite.
>  Reduce the usage of external tools in the tox test suite

- .github/workflows/weekly-integration-test.yml
This PR adds the missing package to CI.
> Fix CI Dependency

- openscap_report/report_generators/html_templates/base_report.html
- openscap_report/report_generators/html_templates/template_report.html
This PR changes title of the report.
Fixes: #181
> Report Title

- openscap_report/report_generators/html_templates/base_report.html
- openscap_report/report_generators/html_templates/oval_definition_detail.html
- openscap_report/report_generators/html_templates/oval_graph.html
- openscap_report/report_generators/html_templates/rule_detail.html
- openscap_report/report_generators/html_templates/rules_overview.html
- openscap_report/report_generators/html_templates/search_input.html
- openscap_report/report_generators/html_templates/summary_banner.html
This PR fixes minor bugs in the HTML templates and changes the layout of the rule detail and OVAL definition detail fields.
> Rearrange fields in Rule detail and OVAL definition detail

- openscap_report/report_generators/html_templates/cpe_graph.html
- openscap_report/report_generators/html_templates/js/interactive_script.js
- openscap_report/report_generators/html_templates/js/oval_graph_generation_script.js
- openscap_report/report_generators/html_templates/oval_definition_detail.html
This PR adds a title with information about the type of check. Checks matching the applicability are collapsed for convenience.
> Distinguish Between Configuration OVAL And Applicability Checks

- openscap_report/scap_results_parser/parsers/__init__.py
- openscap_report/scap_results_parser/parsers/known_references.py
- openscap_report/scap_results_parser/parsers/rule_parser.py
This PR allows using known references from `Benchmark/reference` elements.
> Add function to update of known references

- tox.ini
This PR requires Python code style checks in tox.
> Require Python code style checks

- openscap_report/dataclasses/dataclasses.py
- tests/unit_tests/test_shared_static_methods_of_parser.py
Adressing pylint errors.
For more details, please read commit messages of each commit
> Fix pylint problems
